### Please submit a Jupyter notebook with the name format:
### "Data88_Homework1_LASTNAME.ipynb"
### Use the "markdown" mode for written answers and include comments and notes as appropriate

In [2]:
import numpy as np
import datascience as ds
import pandas as pd

### Problem 1
`Create a 4-state transition matrix with the following probabilities...`<br>
#### State 1: 90% to 1, 10% to 2, 0% to 3, 0% to 4
#### State 2: 25% to 1, 70% to 2, 5% to 3, 0% to 4
#### State 3: 0% to 1, 5% to 2, 70% to 3, 25% to 4
#### State 4: 0% to 1, 0% to 2, 10% to 3, 90% to 4

<br>
<br>

### Observe this state space over different forward periods <br>
### Describe the behavior over short- and long-run periods <br>
### Are there any real-world state phenomena like this?

In [13]:
state = np.array([[0.9, 0.1, 0.0, 0.0], [0.25, 0.7, 0.05, 0.0], [0.0, 0.05, 0.7, 0.25], [0.0, 0.0, 0.1, 0.9]])
state

array([[0.9 , 0.1 , 0.  , 0.  ],
       [0.25, 0.7 , 0.05, 0.  ],
       [0.  , 0.05, 0.7 , 0.25],
       [0.  , 0.  , 0.1 , 0.9 ]])

In [26]:
state_10 = np.linalg.matrix_power(state, 10)
state_50 = np.linalg.matrix_power(state, 50)
state_75 = np.linalg.matrix_power(state, 75)
state_100 = np.linalg.matrix_power(state, 100)
state_1000 = np.linalg.matrix_power(state, 1000)
print("state at 10:", state_10)
print(" ")
print("state at 50:", state_50)
print(" ")
print("state at 100:", state_100)
print(" ")
print("state at 1000:", state_1000)

state at 10: [[0.67893433 0.23829705 0.04357073 0.03919789]
 [0.59574263 0.22412558 0.07120495 0.10892683]
 [0.10892683 0.07120495 0.22412558 0.59574263]
 [0.03919789 0.04357073 0.23829705 0.67893433]]
 
state at 50: [[0.48084268 0.18073722 0.10497707 0.23344303]
 [0.45184304 0.17185678 0.11385751 0.26244267]
 [0.26244267 0.11385751 0.17185678 0.45184304]
 [0.23344303 0.10497707 0.18073722 0.48084268]]
 
state at 100: [[0.39492065 0.15442568 0.13128861 0.31936506]
 [0.38606419 0.1517136  0.13400068 0.32822152]
 [0.32822152 0.13400068 0.1517136  0.38606419]
 [0.31936506 0.13128861 0.15442568 0.39492065]]
 
state at 1000: [[0.35714286 0.14285714 0.14285714 0.35714286]
 [0.35714286 0.14285714 0.14285714 0.35714286]
 [0.35714286 0.14285714 0.14285714 0.35714286]
 [0.35714286 0.14285714 0.14285714 0.35714286]]


In [ ]:
#In the short run, the matrix shows the probability of transitioning to each state, over long run periods, the probability for each state converges to the same number. A real life example of this would be if four different colleges had these acceptance rates, and over thousands of applicants, their actual acceptance rate more accurately represents this projected acceptance rate.

### Problem 2

#### Describe a potential State, and Event space for a basketball, or football posession (your choice).<br>
#### That is, what are the sets of States and transition Events between states you might model?

In [17]:
### Football posession showing {down, line of scrimmage, yards to gain}
#1) {1st, own-25, 10} Default start condition
#2) {1st, own-25, 10} -> {2nd, own-29, 6}: Halfback rush for 4 yards
#3) {2nd, own-29, 6} -> {3rd, own-31, 4}: Quarterback pass complete to Tight End for 2 yards
#4) {3rd, own-31, 4} -> {4th, own-31, 4}: Quarterback pass incomplete to Wide Receiver for 0 yards
#5) {4th, own-31, 4} -> {Change of possession}: Punter punts to the opponent's 25, end of posession